const mcq = {
  mcqSidebar: [
    {
      type: 'category',
      label: 'MCQs',
      collapsed: true,
      items: [
        'mcq/mcq-home',
        {
          type: 'category',
          label: 'Basic MCQs',
          collapsed: true,
          items: [
            'mcq/cpp_mcqs',
            'mcq/questions/basic/array-and-strings',
            'mcq/questions/basic/basic',
            'mcq/questions/basic/control-flow',
            'mcq/questions/basic/data-types',
            'mcq/questions/basic/functions',
            'mcq/questions/basic/intro-to-cpp',
            'mcq/questions/basic/io',
            'mcq/questions/basic/loop',
            'mcq/questions/basic/pointers-strings',
            'mcq/questions/basic/variables-and-constants',
            'mcq/questions/basic/pointers-and-references',
          ],
        },
        {
          type: 'category',
          label: 'Intermediate MCQs',
          items: [
            'mcq/questions/intermediate/abstraction',
            'mcq/questions/intermediate/classes-objects',
            'mcq/questions/intermediate/constructors-destructors',
            'mcq/questions/intermediate/encapsulation',
            'mcq/questions/intermediate/file-handling',
            'mcq/questions/intermediate/friend-functions',
            'mcq/questions/intermediate/inheritance',
            'mcq/questions/intermediate/getting-started-with-oops-concept',
            'mcq/questions/intermediate/memory-management',
            'mcq/questions/intermediate/oop',
            'mcq/questions/intermediate/operator-overloading',
            'mcq/questions/intermediate/polymorphism',
          ],
        },
        {
          type: 'category',
          label: 'Advanced MCQs',
          items: [
            'mcq/questions/advanced/concurrency-and-synchronization',
            'mcq/questions/advanced/cpp-features-11-14-17-20',
            'mcq/questions/advanced/exception-handling',
            'mcq/questions/advanced/lambdas',
            'mcq/questions/advanced/move-semantics',
            'mcq/questions/advanced/multithreading',
            'mcq/questions/advanced/stl',
            'mcq/questions/advanced/templates',
            'mcq/questions/advanced/vectors',
          ],
        },
        {
          type: 'category',
          label: 'Specialized MCQs',
          items: [
            'mcq/questions/specialized/algorithm',
            'mcq/questions/specialized/cpp-embedded',
            'mcq/questions/specialized/design-patterns',
            'mcq/questions/specialized/optimization',
            'mcq/questions/specialized/smart-pointers',
            'mcq/questions/specialized/specialized',
          ],
        },
        {
          type: 'category',
          label: 'Interview Questions',
          items: [
            'mcq/interview_question/cpp_interview_mcqs',
            'mcq/interview_question/basic/intro-to-cpp',
            'mcq/interview_question/basic/control-flow',
            'mcq/interview_question/basic/functions-recursion',
            'mcq/interview_question/basic/arrays-strings',
            'mcq/interview_question/basic/io-operations',
            'mcq/interview_question/basic/pointers-references',
            'mcq/interview_question/basic/data-types-variables',
            'mcq/interview_question/intermediate/classes-object',
            'mcq/interview_question/intermediate/constructors-destructors',
            'mcq/interview_question/intermediate/inheritance-polymorphism',
            'mcq/interview_question/intermediate/oop',
            'mcq/interview_question/intermediate/exception-handling',
            'mcq/interview_question/intermediate/memory-management',
            'mcq/interview_question/intermediate/operator-overloading',
            'mcq/interview_question/advanced/templates',
            'mcq/interview_question/advanced/modern-cpp-features',
            'mcq/interview_question/advanced/multi-threading',
            'mcq/interview_question/advanced/stl',
            'mcq/interview_question/advanced/lambda-expressions',
            'mcq/interview_question/advanced/optimization-debugging',
            'mcq/interview_question/advanced/algorithms-design-patterns',
            'mcq/interview_question/standard/modern-cpp',
            'mcq/interview_question/standard/stl-algorithms',
            'mcq/interview_question/specialized/cpp-embedded',
            'mcq/interview_question/specialized/debugging-profiling',
            'mcq/interview_question/specialized/memory-management-detail',
            'mcq/interview_question/specialized/high-performance',
            'mcq/interview_question/specialized/debugging-profiling',
            'mcq/interview_question/specialized/high-performance',
            'mcq/interview_question/specialized/smart-pointers',
            'mcq/interview_question/cpp11/cpp11',
            'mcq/interview_question/cpp14/cpp14',
            'mcq/interview_question/cpp20/cpp20',
          ],
        },
        {
          type: 'category',
          label: 'Interview Questions',
          items: [
            'mcq/interview_question/advanced/stl',
          ],
        },
        {
          type: 'category',
          label: 'Standard Questions',
          items: [
            'mcq/interview_question/cpp11/cpp11',
          ],
        },
      ],
    },
  ],

  dailyMcqSidebar: [
    {
      type: 'category',
      label: 'Daily Mixed MCQ Series',
      collapsed: false,
      items: [
        'mcq/daily/daily-mcq-home',
        'mcq/daily/daily-mcq-day-01',
        'mcq/daily/daily-mcq-day-02',
        'mcq/daily/daily-mcq-day-03',
        'mcq/daily/daily-mcq-day-04',
        'mcq/daily/daily-mcq-day-05',
        'mcq/daily/daily-mcq-day-06',
        'mcq/daily/daily-mcq-day-07',
        'mcq/daily/daily-mcq-day-08',
        'mcq/daily/daily-mcq-day-09',
        'mcq/daily/daily-mcq-day-10',
        'mcq/daily/daily-mcq-day-11',
        'mcq/daily/daily-mcq-day-12',
        'mcq/daily/daily-mcq-day-13',
        'mcq/daily/daily-mcq-day-14',
        'mcq/daily/daily-mcq-day-15',
        'mcq/daily/daily-mcq-day-16',
        'mcq/daily/daily-mcq-day-17',
        'mcq/daily/daily-mcq-day-18',
        'mcq/daily/daily-mcq-day-19',
        'mcq/daily/daily-mcq-day-20',
        'mcq/daily/daily-mcq-day-21',
        'mcq/daily/daily-mcq-day-22',
        'mcq/daily/daily-mcq-day-23',
        'mcq/daily/daily-mcq-day-24',
        'mcq/daily/daily-mcq-day-25',
        'mcq/daily/daily-mcq-day-26',
        'mcq/daily/daily-mcq-day-27',
        'mcq/daily/daily-mcq-day-28',
        'mcq/daily/daily-mcq-day-29',
        'mcq/daily/daily-mcq-day-30',
        'mcq/daily/daily-mcq-day-31',
        'mcq/daily/daily-mcq-day-32',
        'mcq/daily/daily-mcq-day-33',
        'mcq/daily/daily-mcq-day-34',
        'mcq/daily/daily-mcq-day-35',
        'mcq/daily/daily-mcq-day-36',
        'mcq/daily/daily-mcq-day-37',
        'mcq/daily/daily-mcq-day-38',
        'mcq/daily/daily-mcq-day-39',
        'mcq/daily/daily-mcq-day-40',
        'mcq/daily/daily-mcq-day-41',
        'mcq/daily/daily-mcq-day-42',
        'mcq/daily/daily-mcq-day-43',
        'mcq/daily/daily-mcq-day-44',
        'mcq/daily/daily-mcq-day-45',
        'mcq/daily/daily-mcq-day-46',
        'mcq/daily/daily-mcq-day-47',
        'mcq/daily/daily-mcq-day-48',
        'mcq/daily/daily-mcq-day-49',
        'mcq/daily/daily-mcq-day-50',
        'mcq/daily/daily-mcq-day-51',
        'mcq/daily/daily-mcq-day-52',
        'mcq/daily/daily-mcq-day-53',
        'mcq/daily/daily-mcq-day-54',
        'mcq/daily/daily-mcq-day-55',
        'mcq/daily/daily-mcq-day-56',
        'mcq/daily/daily-mcq-day-57',
        'mcq/daily/daily-mcq-day-58',
        'mcq/daily/daily-mcq-day-59',
        'mcq/daily/daily-mcq-day-60',
        'mcq/daily/daily-mcq-day-61',
        'mcq/daily/daily-mcq-day-62',
        'mcq/daily/daily-mcq-day-63',
        'mcq/daily/daily-mcq-day-64',
        'mcq/daily/daily-mcq-day-65',
        'mcq/daily/daily-mcq-day-66',
        'mcq/daily/daily-mcq-day-67',
        'mcq/daily/daily-mcq-day-68',
        'mcq/daily/daily-mcq-day-69',
        'mcq/daily/daily-mcq-day-70',
        'mcq/daily/daily-mcq-day-71',
        'mcq/daily/daily-mcq-day-72',
        'mcq/daily/daily-mcq-day-73',
        'mcq/daily/daily-mcq-day-74',
        'mcq/daily/daily-mcq-day-75',
        'mcq/daily/daily-mcq-day-76',
        'mcq/daily/daily-mcq-day-77',
        'mcq/daily/daily-mcq-day-78',
        'mcq/daily/daily-mcq-day-79',
        'mcq/daily/daily-mcq-day-80',
        'mcq/daily/daily-mcq-day-81',
        'mcq/daily/daily-mcq-day-82',
        'mcq/daily/daily-mcq-day-83',
        'mcq/daily/daily-mcq-day-84',
        'mcq/daily/daily-mcq-day-85',
        'mcq/daily/daily-mcq-day-86',
        'mcq/daily/daily-mcq-day-87',
        'mcq/daily/daily-mcq-day-88',
        'mcq/daily/daily-mcq-day-89',
        'mcq/daily/daily-mcq-day-90',
        'mcq/daily/daily-mcq-day-91',
        'mcq/daily/daily-mcq-day-92',
        'mcq/daily/daily-mcq-day-93',
        'mcq/daily/daily-mcq-day-94',
        'mcq/daily/daily-mcq-day-95',
        'mcq/daily/daily-mcq-day-96',
        'mcq/daily/daily-mcq-day-97',
        'mcq/daily/daily-mcq-day-98',
        'mcq/daily/daily-mcq-day-99',
        'mcq/daily/daily-mcq-day-100',
      ],
    },
  ],

  reactMcqSidebar: [
    {
      type: 'category',
      label: 'React MCQs',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Basic React MCQs',
          collapsed: true,
          items: [
            'react_mcq/react_mcq',
            'react_mcq/basic/intro-to-react',
            'react_mcq/basic/jsx',
            'react_mcq/basic/components',
            'react_mcq/basic/props-state',
            'react_mcq/basic/events',
            'react_mcq/basic/conditional-rendering',
            'react_mcq/basic/lists-keys',
            'react_mcq/basic/forms',
          ],
        },
        {
          type: 'category',
          label: 'Intermediate React MCQs',
          collapsed: true,
          items: [
            'react_mcq/intermediate/lifecycle',
            'react_mcq/intermediate/hooks',
            'react_mcq/intermediate/effects',
            'react_mcq/intermediate/router',
            'react_mcq/intermediate/lifting-state',
            'react_mcq/intermediate/refs',
            'react_mcq/intermediate/controlled-uncontrolled',
          ],
        },
        {
          type: 'category',
          label: 'Advanced React MCQs',
          collapsed: true,
          items: [
            'react_mcq/advanced/custom-hooks',
            'react_mcq/advanced/context-api',
            'react_mcq/advanced/use-reducer',
            'react_mcq/advanced/memoization',
            'react_mcq/advanced/lazy-loading',
            'react_mcq/advanced/error-boundaries',
            'react_mcq/advanced/portals',
            'react_mcq/advanced/suspense',
          ],
        },
        {
          type: 'category',
          label: 'Specialized React MCQs',
          collapsed: true,
          items: [
            'react_mcq/specialized/redux',
            'react_mcq/specialized/performance',
            'react_mcq/specialized/testing',
            'react_mcq/specialized/typescript',
            'react_mcq/specialized/production',
          ],
        },
      ],
    },
  ],

  domainMcqSidebar: [
    {
      type: 'category',
      label: 'Domain Specific MCQs',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'COA MCQs',
          collapsed: true,
          items: [
            'mcq/questions/domain/coa/coa-home',
            'mcq/questions/domain/coa/coa-quiz',
            'mcq/questions/domain/coa/basic-terminology-home',
            'mcq/questions/domain/coa/basic-terminology-quiz',
            'mcq/questions/domain/coa/architecture-vs-organization-home',
            'mcq/questions/domain/coa/architecture-vs-organization-quiz',
            'mcq/questions/domain/coa/instruction-flow-modern-cpu-home',
            'mcq/questions/domain/coa/instruction-flow-modern-cpu-quiz',
          ],
        },
        {
          type: 'category',
          label: 'Compiler MCQs',
          collapsed: true,
          items: [
            'mcq/questions/domain/compilers/compiler-stack-home',
            'mcq/questions/domain/compilers/compiler/compiler-track-home',
            'mcq/questions/domain/compilers/compiler/compiler-basics',
            'mcq/questions/domain/compilers/compiler/compiler-lexer-quiz',
            'mcq/questions/domain/compilers/compiler/compiler-commands',
            'mcq/questions/domain/compilers/compiler/compiler-ir',
            'mcq/questions/domain/compilers/compiler/compiler-backend',
            'mcq/questions/domain/compilers/compiler/compiler-track-quiz',
            'mcq/questions/domain/compilers/llvm/llvm-track-home',
            'mcq/questions/domain/compilers/llvm/llvm-track-quiz',
            'mcq/questions/domain/compilers/mlir/mlir-track-home',
            'mcq/questions/domain/compilers/mlir/mlir-track-quiz',
            'mcq/questions/domain/compilers/ai-in-compilers/ai-in-compilers-home',
            'mcq/questions/domain/compilers/ai-in-compilers/ai-in-compilers-quiz',
            'mcq/questions/domain/compilers/ai-compiler/compilers-in-ai-home',
            'mcq/questions/domain/compilers/ai-compiler/compilers-in-ai-quiz',
            'mcq/questions/domain/compiler-dev/compiler-dev-home',
            'mcq/questions/domain/compiler-dev/compiler-dev-fundamentals',
            'mcq/questions/domain/compiler-dev/compiler-dev-parsing-ir',
            'mcq/questions/domain/compiler-dev/compiler-dev-llvm-optimization',
            'mcq/questions/domain/compiler-dev/compiler-dev-quiz',
          ],
        },
        {
          type: 'category',
          label: 'System Programming MCQs',
          collapsed: true,
          items: [
            'mcq/questions/domain/system-programming/system-programming-home',
            'mcq/questions/domain/system-programming/c-memory-layout-mcqs',
            'mcq/questions/domain/system-programming/system-programming-quiz',
          ],
        },
        {
          type: 'category',
          label: 'GPU Programming MCQs',
          collapsed: true,
          items: [
            'mcq/questions/domain/gpu-programming/gpu-programming-home',
            'mcq/questions/domain/gpu-programming/gpu-programming-quiz',
          ],
        },
        {
          type: 'category',
          label: 'Embedded Systems MCQs',
          collapsed: true,
          items: [
            'mcq/questions/domain/embedded/embedded-home',
            'mcq/questions/domain/embedded/embedded-quiz',
          ],
        },
        {
          type: 'category',
          label: 'HPC and Performance MCQs',
          collapsed: true,
          items: [
            'mcq/questions/domain/data-science-hpc/hpc-home',
            'mcq/questions/domain/data-science-hpc/hpc-quiz',
          ],
        },
        {
          type: 'category',
          label: 'Competitive Programming MCQs',
          collapsed: true,
          items: [
            'mcq/questions/domain/competitive-programming/competitive-programming-home',
            'mcq/questions/domain/competitive-programming/competitive-programming-quiz',
          ],
        },
        {
          type: 'category',
          label: 'Parallel Programming MCQs',
          collapsed: true,
          items: [
            { type: 'link', label: 'Start Here MCQs', href: '/docs/mcq/questions/domain/parallel/start-here/' },
            { type: 'link', label: 'Chapter 1: Parallel Thinking MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-1/' },
            { type: 'link', label: 'Chapter 2: CPU Parallelism MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-2/' },
            { type: 'link', label: 'Chapter 3: OpenMP MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-3/' },
            { type: 'link', label: 'Chapter 4: Parallel Algorithms MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-4/' },
            { type: 'link', label: 'Chapter 5: SIMD MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-5/' },
            { type: 'link', label: 'Chapter 6: GPU Programming MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-6/' },
            { type: 'link', label: 'Chapter 7: Distributed Computing MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-7/' },
            { type: 'link', label: 'Chapter 8: Measuring MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-8/' },
            { type: 'link', label: 'Projects MCQs', href: '/docs/mcq/questions/domain/parallel/projects/' },
          ],
        },
      ],
    },
  ],

  compilerMcqSidebar: [
    {
      type: 'category',
      label: 'Compiler Design MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/compiler-dev/compiler-dev-home',
        'mcq/questions/domain/compiler-dev/compiler-dev-quiz',
      ],
    },
  ],

  coaMcqSidebar: [
    {
      type: 'category',
      label: 'COA MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/coa/coa-home',
        'mcq/questions/domain/coa/coa-quiz',
        'mcq/questions/domain/coa/basic-terminology-home',
        'mcq/questions/domain/coa/basic-terminology-quiz',
        'mcq/questions/domain/coa/architecture-vs-organization-home',
        'mcq/questions/domain/coa/architecture-vs-organization-quiz',
        'mcq/questions/domain/coa/instruction-flow-modern-cpu-home',
        'mcq/questions/domain/coa/instruction-flow-modern-cpu-quiz',
      ],
    },
  ],

  systemProgrammingMcqSidebar: [
    {
      type: 'category',
      label: 'System Programming MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/system-programming/system-programming-home',
        'mcq/questions/domain/system-programming/c-memory-layout-mcqs',
        'mcq/questions/domain/system-programming/system-programming-quiz',
      ],
    },
  ],

  gpuMcqSidebar: [
    {
      type: 'category',
      label: 'GPU Programming MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/gpu-programming/gpu-programming-home',
        'mcq/questions/domain/gpu-programming/gpu-programming-quiz',
      ],
    },
  ],

  embeddedMcqSidebar: [
    {
      type: 'category',
      label: 'Embedded Systems MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/embedded/embedded-home',
        'mcq/questions/domain/embedded/embedded-quiz',
      ],
    },
  ],

  hpcMcqSidebar: [
    {
      type: 'category',
      label: 'HPC and Performance MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/data-science-hpc/hpc-home',
        'mcq/questions/domain/data-science-hpc/hpc-quiz',
      ],
    },
  ],

  competitiveProgrammingMcqSidebar: [
    {
      type: 'category',
      label: 'Competitive Programming MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/competitive-programming/competitive-programming-home',
        'mcq/questions/domain/competitive-programming/competitive-programming-quiz',
      ],
    },
  ],

  compilerStackMcqSidebar: [
    {
      type: 'category',
      label: 'Compiler MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/compilers/compiler-stack-home',
        'mcq/questions/domain/compilers/compiler/compiler-track-home',
        'mcq/questions/domain/compilers/llvm/llvm-track-home',
        'mcq/questions/domain/compilers/mlir/mlir-track-home',
        'mcq/questions/domain/compilers/ai-in-compilers/ai-in-compilers-home',
        'mcq/questions/domain/compilers/ai-compiler/compilers-in-ai-home',
        'mcq/questions/domain/compiler-dev/compiler-dev-home',
      ],
    },
  ],

  compilerTrackMcqSidebar: [
    {
      type: 'category',
      label: 'Compilers MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/compilers/compiler/compiler-track-home',
        'mcq/questions/domain/compilers/compiler/compiler-basics',
        'mcq/questions/domain/compilers/compiler/compiler-commands',
        'mcq/questions/domain/compilers/compiler/compiler-ir',
        'mcq/questions/domain/compilers/compiler/compiler-backend',
        'mcq/questions/domain/compilers/compiler/compiler-track-quiz',
      ],
    },
  ],

  llvmTrackMcqSidebar: [
    {
      type: 'category',
      label: 'LLVM MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/compilers/llvm/llvm-clang-frontend-quiz',
        'mcq/questions/domain/compilers/llvm/llvm-track-quiz',
        'mcq/questions/domain/compilers/llvm/llvm-pass-plugin-quiz',
      ],
    },
  ],

  mlirTrackMcqSidebar: [
    {
      type: 'category',
      label: 'MLIR MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/compilers/mlir/mlir-track-home',
        'mcq/questions/domain/compilers/mlir/mlir-track-quiz',
      ],
    },
  ],

  aiInCompilersTrackMcqSidebar: [
    {
      type: 'category',
      label: 'AI in Compilers MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/compilers/ai-in-compilers/ai-in-compilers-home',
        'mcq/questions/domain/compilers/ai-in-compilers/ai-in-compilers-quiz',
      ],
    },
  ],

  compilersInAiTrackMcqSidebar: [
    {
      type: 'category',
      label: 'Compilers in AI MCQs',
      collapsed: false,
      items: [
        'mcq/questions/domain/compilers/ai-compiler/compilers-in-ai-home',
        'mcq/questions/domain/compilers/ai-compiler/compilers-in-ai-quiz',
      ],
    },
  ],

  parallelMcqHomeSidebar: [
    {
      type: 'category',
      label: 'Parallel Programming MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/index' },
      items: [
        { type: 'link', label: 'Start Here MCQs', href: '/docs/mcq/questions/domain/parallel/start-here/' },
        { type: 'link', label: 'Chapter 1: Parallel Thinking MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-1/' },
        { type: 'link', label: 'Chapter 2: CPU Parallelism MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-2/' },
        { type: 'link', label: 'Chapter 3: OpenMP MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-3/' },
        { type: 'link', label: 'Chapter 4: Parallel Algorithms MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-4/' },
        { type: 'link', label: 'Chapter 5: SIMD MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-5/' },
        { type: 'link', label: 'Chapter 6: GPU Programming MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-6/' },
        { type: 'link', label: 'Chapter 7: Distributed Computing MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-7/' },
        { type: 'link', label: 'Chapter 8: Measuring MCQs', href: '/docs/mcq/questions/domain/parallel/chapter-8/' },
        { type: 'link', label: 'Projects MCQs', href: '/docs/mcq/questions/domain/parallel/projects/' },
      ],
    },
  ],
  parallelMcqStartSidebar: [
    {
      type: 'category',
      label: 'Start Here MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/start-here/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/start-here/quiz',
      ],
    },
  ],
  parallelMcqChapter1Sidebar: [
    {
      type: 'category',
      label: 'Chapter 1: Parallel Thinking MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/chapter-1/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/chapter-1/quiz',
      ],
    },
  ],
  parallelMcqChapter2Sidebar: [
    {
      type: 'category',
      label: 'Chapter 2: CPU Parallelism MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/chapter-2/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/chapter-2/quiz',
      ],
    },
  ],
  parallelMcqChapter3Sidebar: [
    {
      type: 'category',
      label: 'Chapter 3: OpenMP MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/chapter-3/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/chapter-3/quiz',
      ],
    },
  ],
  parallelMcqChapter4Sidebar: [
    {
      type: 'category',
      label: 'Chapter 4: Parallel Algorithms MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/chapter-4/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/chapter-4/quiz',
      ],
    },
  ],
  parallelMcqChapter5Sidebar: [
    {
      type: 'category',
      label: 'Chapter 5: SIMD MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/chapter-5/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/chapter-5/quiz',
      ],
    },
  ],
  parallelMcqChapter6Sidebar: [
    {
      type: 'category',
      label: 'Chapter 6: GPU Programming MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/chapter-6/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/chapter-6/quiz',
      ],
    },
  ],
  parallelMcqChapter7Sidebar: [
    {
      type: 'category',
      label: 'Chapter 7: Distributed Computing MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/chapter-7/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/chapter-7/quiz',
      ],
    },
  ],
  parallelMcqChapter8Sidebar: [
    {
      type: 'category',
      label: 'Chapter 8: Measuring MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/chapter-8/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/chapter-8/quiz',
      ],
    },
  ],
  parallelMcqProjectsSidebar: [
    {
      type: 'category',
      label: 'Projects MCQs',
      collapsed: false,
      link: { type: 'doc', id: 'mcq/questions/domain/parallel/projects/index' },
      items: [
        { type: 'link', label: 'All parallel quizzes', href: '/docs/mcq/questions/domain/parallel/' },
        'mcq/questions/domain/parallel/projects/quiz',
      ],
    },
  ],

};

module.exports = mcq;
